version: "3.1"


services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_USER: "denis"
      MYSQL_DATABASE: "mydbs"
    ports:
      - 3306:3306
    volumes:
      - devdojo_data:/var/lib/mysql
volumes:
  devdojo_data:

      